version: "3.9"
services:
  mysql:
    image: mysql:8.0.30-oracle
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aDevPassword
    volumes:
      - datavolume:/var/lib/mysql
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080

volumes:
  datavolume: